//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 Netflix, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	resourcepoolv1 "github.com/Netflix/titus-controllers-api/api/resourcepool/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Demand) DeepCopyInto(out *Demand) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Demand.
func (in *Demand) DeepCopy() *Demand {
	if in == nil {
		return nil
	}
	out := new(Demand)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Demand) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DemandList) DeepCopyInto(out *DemandList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Demand, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DemandList.
func (in *DemandList) DeepCopy() *DemandList {
	if in == nil {
		return nil
	}
	out := new(DemandList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DemandList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DemandSpec) DeepCopyInto(out *DemandSpec) {
	*out = *in
	if in.Reservations != nil {
		in, out := &in.Reservations, &out.Reservations
		*out = make(ResourceGroups, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DemandSpec.
func (in *DemandSpec) DeepCopy() *DemandSpec {
	if in == nil {
		return nil
	}
	out := new(DemandSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DemandStatus) DeepCopyInto(out *DemandStatus) {
	*out = *in
	if in.Bound != nil {
		in, out := &in.Bound, &out.Bound
		*out = make(map[ResourcePoolName]resourcepoolv1.ComputeResource, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Unbound != nil {
		in, out := &in.Unbound, &out.Unbound
		*out = make(map[ResourcePoolName]ResourceGroups, len(*in))
		for key, val := range *in {
			var outVal []ResourceGroup
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make(ResourceGroups, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	if in.ReservedUnallocated != nil {
		in, out := &in.ReservedUnallocated, &out.ReservedUnallocated
		*out = make(map[ResourcePoolName]ResourceGroups, len(*in))
		for key, val := range *in {
			var outVal []ResourceGroup
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make(ResourceGroups, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DemandStatus.
func (in *DemandStatus) DeepCopy() *DemandStatus {
	if in == nil {
		return nil
	}
	out := new(DemandStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceGroup) DeepCopyInto(out *ResourceGroup) {
	*out = *in
	out.ComputeResource = in.ComputeResource
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceGroup.
func (in *ResourceGroup) DeepCopy() *ResourceGroup {
	if in == nil {
		return nil
	}
	out := new(ResourceGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in ResourceGroups) DeepCopyInto(out *ResourceGroups) {
	{
		in := &in
		*out = make(ResourceGroups, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceGroups.
func (in ResourceGroups) DeepCopy() ResourceGroups {
	if in == nil {
		return nil
	}
	out := new(ResourceGroups)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Trough) DeepCopyInto(out *Trough) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Trough.
func (in *Trough) DeepCopy() *Trough {
	if in == nil {
		return nil
	}
	out := new(Trough)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Trough) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TroughList) DeepCopyInto(out *TroughList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Trough, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TroughList.
func (in *TroughList) DeepCopy() *TroughList {
	if in == nil {
		return nil
	}
	out := new(TroughList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TroughList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TroughSpec) DeepCopyInto(out *TroughSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TroughSpec.
func (in *TroughSpec) DeepCopy() *TroughSpec {
	if in == nil {
		return nil
	}
	out := new(TroughSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TroughStatus) DeepCopyInto(out *TroughStatus) {
	*out = *in
	if in.Capacity != nil {
		in, out := &in.Capacity, &out.Capacity
		*out = new(resourcepoolv1.ComputeResource)
		**out = **in
	}
	if in.Allocatable != nil {
		in, out := &in.Allocatable, &out.Allocatable
		*out = new(resourcepoolv1.ComputeResource)
		**out = **in
	}
	if in.Free != nil {
		in, out := &in.Free, &out.Free
		*out = new(resourcepoolv1.ComputeResource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TroughStatus.
func (in *TroughStatus) DeepCopy() *TroughStatus {
	if in == nil {
		return nil
	}
	out := new(TroughStatus)
	in.DeepCopyInto(out)
	return out
}
